spring:
  datasource:
    url: jdbc:postgresql://postgres-todo:5432/todo_db
    username: todo_user
    password: todo_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.example.todo: DEBUG

server:
  port: 8080
  # On enlève le context-path pour simplifier le healthcheck et correspondre au docker-compose